const PROXY_CONFIG = [
  {
    context: [
      '/en/api',
     // '/api',
      '/oauth',
      '/session',
      '/user',
      '/sites',
      '/admin',
      '/manage',
      '/system',
      '/core',
      '/libraries',
      '/modules',
      '/themes',
      '/shs-term-data',
      '/contextual',
      '/webform_rest',
      '/quickedit',
      '/history',
      '/media-library',
      '/autocomplete',
      '/entity_reference_autocomplete',
      '/views/ajax',
      '/batch',
      '/editor',
      '/export',
      '/print',
      '/wechat',
      '/media',
      '/assets/app',
    ],
    target: 'https://base.builder.design',
    secure: false,
    changeOrigin: true,
  },
  {
    context: ['/app-api'],
    //target: 'https://localhost:44388',
    target: 'http://newapi.lightcomm.com',
    secure: false,
    changeOrigin: true,
    // pathRewrite: {
    //   '^/app-api': '/api/app',
    // },
  },
];

module.exports = PROXY_CONFIG;
